name: Template - Run claat

on:
  workflow_dispatch:

jobs:
  generate-codelab:
    runs-on: ubuntu-latest
    steps:
      - name: Download Source Code (git)
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Generate Code Labs Content
        uses: ./.github/actions/claat
        with:
          client-id: ${{ secrets.clientId }}
          client-secret: ${{ secrets.clientSecret }}
          refresh-token: ${{ secrets.refreshToken }}          
          doc-id: 1vr9zrrtGbCUvgm5c_L_ogO5UfT5yE_l3jos2cDYBrBI
        