name: Website - Publish Content

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: npm install
    - run: gulp dist

    - run: |
        date > dist/generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Action: ${{ github.workflow }} # ${{ github.run_number }}"
        git push
